main: ${mainClass}
name: ${name}
version: ${version}
api-version: 1.13
authors: [StupidDrew9, royalkingkb]
depend: [Towny]
commands:
  endportal:
    permission: mcatlas.command.endportal
    description: View or manage an End Portal
  endworlds:
    permission: mcatlas.command.endworlds
    description: View currently active End Worlds
