main: ${mainClass}
name: ${name}
version: ${version}
api-version: 1.13
authors: [StupidDrew9, royalkingkb]
commands:
  endportal:
    permission: Manage End Portals
    description: mcatlas.command.endportal
